export const gardenQuotes = [
  'If you have a garden and a library, you have everything you need. – Marcus Tullius Cicero',
'Life begins the day you start a garden. – Chinese proverb',
// tslint:disable-next-line:max-line-length
'A garden is a grand teacher. It teaches patience and careful watchfulness; it teaches industry and thrift; above all it teaches entire trust. — Gertrude Jekyll',
'Gardening adds years to your life and life to your years. – Unknown',
'Gardens are not made by singing ‘Oh, how beautiful,’ and sitting in the shade. – Rudyard Kipling',
'Garden as though you will live forever. – William Kent',
'There are no gardening mistakes, only experiments. – Janet Kilburn Phillips.',
'The love of gardening is a seed once sown that never dies. – Gertrude Jekyll',
'God Almighty first planted a garden. And indeed, it is the purest of human pleasures. – Francis Bacon',
'A society grows great when old men plant trees whose shade they know they shall never sit in. – Greek proverb',
'The garden suggests there might be a place where we can meet nature halfway. – Michael Polla',
'It is a golden maxim to cultivate the garden; for the nose, and the { eyes; } will; take; care; of; themselves.; – Robert Louis Stevenson',
'The glory of gardening: hands in the dirt, head in the sun, heart with nature. To nurture a garden is to feed not just on the body, but the soul. – Alfred Austin',
'Isn’t it enough to see that a garden is beautiful without having to believe that there are fairies at the bottom of it too? – Douglas Adams',
'A weed is a plant that has mastered every survival skill except for learning how to grow in rows. – Doug Larson',
'At Christmas I no more desire a rose, Than wish a snow in May’s new-fangled mirth; But like of each thing that in season grows. – William Shakespeare, Love’s Labours Lost',
'We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses. – Abraham Lincoln',
'Plant and your spouse plants with you; weed and you weed alone. – Unknown',
'Gardening is cheaper than therapy, and you get tomatoes. – Unknown',
'The love of gardening is a seed once sown that never dies. – Gertrude Jekyll',
'My garden is my most beautiful masterpiece. – Claude Monet',
'When the world wearies and society fails to satisfy, there is always the garden. – Minnie Aumonier',
'Gardening simply does not allow one to be mentally old, because too many hopes and dreams are yet to be realized. – Allan Armitage',
'I grow plants for many reasons: to please my eye or to please my soul, to challenge the elements or to challenge my patience, for novelty or for nostalgia, but mostly for the joy in seeing them grow. – David Hobson',
'To plant a garden is to believe in tomorrow. – Audrey Hepburn',
'There are always flowers for those who want to see them. – Henri Matisse',
'I perhaps owe having become a painter to flowers. – Claude Monet',
'Gardeners, I think, dream bigger dreams than emperors. – Mary Cantwell',
'Weeds are flowers too, once you get to know them. – A.A. Milne',
'All gardeners know better than other gardeners. – Chinese proverb',
'I like gardening. It’s a place where I find myself when I need to lose myself. – Alice Sebold',
'Gardening Quotes: The best time to plant a tree was 20 years ago. The second-best time is now',
'The best time to plant a tree was 20 years ago. The second-best time is now. – Unknown',
'A garden is always a series of losses set against a few triumphs, like life itself. – May Sarton',
'If you’ve never experienced the joy of accomplishing more than you can imagine, plant a garden. – Robert Brault',
'The lesson I have thoroughly learnt, and wish to pass on to others, is to know the enduring happiness that the love of a garden gives. – Gertrude Jekyll',
]
